/**********************************************************************
*
*  GEM/3 Programmers Toolkit - Digital Research, Inc.
*
*  Filename: DOODLE.H
*
*  Date: 08/01/89
*
***********************************************************************/

#define DEMOMENU 0  	/* TREE */
#define DEMOINFO 8  	/* OBJECT in TREE #0 */
#define DEMODESK 3  	/* OBJECT in TREE #0 */
#define DEMOFILE 4  	/* OBJECT in TREE #0 */
#define DEMOOPTS 5  	/* OBJECT in TREE #0 */
#define DEMOLOAD 17  	/* OBJECT in TREE #0 */
#define DEMOSAVE 18  	/* OBJECT in TREE #0 */
#define DEMOSVAS 19  	/* OBJECT in TREE #0 */
#define DEMOABAN 20  	/* OBJECT in TREE #0 */
#define DEMOQUIT 21  	/* OBJECT in TREE #0 */
#define DEMOPENS 23  	/* OBJECT in TREE #0 */
#define DEMOERAP 25  	/* OBJECT in TREE #0 */
#define DEMOINFD 1  	/* TREE */
#define DEMOOK 6  	/* OBJECT in TREE #1 */
#define DEMOPEND 3  	/* TREE */
#define DEMOPSOK 10  	/* OBJECT in TREE #3 */
#define DEMOCNCL 12  	/* OBJECT in TREE #3 */
#define DEMOOVWR 0  	/* STRING */
#define DEMONWDW 1  	/* STRING */
#define DEMOSVAD 2  	/* TREE */
#define DEMOSOK 2  	/* OBJECT in TREE #2 */
#define DEMOSCNL 3  	/* OBJECT in TREE #2 */
#define DEMONAME 4  	/* OBJECT in TREE #2 */
#define DEMOIMG 9  	/* OBJECT in TREE #1 */
#define DEMOPCLR 18  	/* OBJECT in TREE #3 */
#define DEMOPFIN 3  	/* OBJECT in TREE #3 */
#define DEMOPMED 4  	/* OBJECT in TREE #3 */
#define DEMOPBRD 5  	/* OBJECT in TREE #3 */
#define DEMOEFIN 6  	/* OBJECT in TREE #3 */
#define DEMOEMED 7  	/* OBJECT in TREE #3 */
#define DEMOEBRD 8  	/* OBJECT in TREE #3 */
#define DCOLBAK 17  	/* OBJECT in TREE #3 */
#define DCOLFWD 16  	/* OBJECT in TREE #3 */
#define DCOL1 19  	/* OBJECT in TREE #3 */
#define DCOL2 20  	/* OBJECT in TREE #3 */
#define DCOL3 21  	/* OBJECT in TREE #3 */
#define DCOL4 22  	/* OBJECT in TREE #3 */
#define DCOLAKT 23  	/* OBJECT in TREE #3 */
