/***********************************************************************
*
*  GEM/3 Programmers Toolkit - Digital Research, Inc.
*
*  Filename: USERDEF.H
*
*  Date: 08/01/89
*
************************************************************************/

#define TEST 0  	/* TREE */
#define RB1 2  	        /* OBJECT in TREE #0 */
#define RB2 3  	        /* OBJECT in TREE #0 */
#define RB3 4  	        /* OBJECT in TREE #0 */
#define RB4 5  	        /* OBJECT in TREE #0 */
#define SB1 10  	/* OBJECT in TREE #0 */
#define SB2 11  	/* OBJECT in TREE #0 */
#define SB3 12  	/* OBJECT in TREE #0 */
#define SB4 13  	/* OBJECT in TREE #0 */
