
#include <portab.h>
#include <machine.h>
#include <dos.h>
						/* in DOSIF.A86		*/

GLOBAL UWORD	DOS_AX;
GLOBAL UWORD	DOS_BX;
GLOBAL UWORD	DOS_CX;
GLOBAL UWORD	DOS_DX;
GLOBAL UWORD	DOS_DS;
GLOBAL UWORD	DOS_ES;
GLOBAL UWORD	DOS_SI;
GLOBAL UWORD	DOS_DI;
GLOBAL UWORD	DOS_ERR;
GLOBAL UWORD    MAK_GEM_DIR;

GLOBAL BYTE	gl_dta[128];
