lc1 geminit -s
lc2 geminit -scode -v
lc1 gemnulp -s
lc2 gemnulp -scode -v
lc1 gemprlib -s
lc2 gemprlib -scode -v
lc1 gemasync -s
lc2 gemasync -scode -v
lc1 gembase -s
lc2 gembase -scode -v
lc1 gemctrl -s
lc2 gemctrl -scode -v
lc1 gemdisp -s
lc2 gemdisp -scode -v
lc1 gemflag -s
lc2 gemflag -scode -v
lc1 geminput -s
lc2 geminput -scode -v
lc1 gempd -s
lc2 gempd -scode -v
lc1 gemqueue -s
lc2 gemqueue -scode -v
lc1 gemwrect -s
lc2 gemwrect -scode -v
lc1 gemdos -s
lc2 gemdos -scode -v
lc1 gemsuper -s
lc2 gemsuper -scode -v
lc1 gemaplib -s
lc2 gemaplib -scode -v
lc1 gemevlib -s
lc2 gemevlib -scode -v
lc1 gemmnlib -s
lc2 gemmnlib -scode -v
lc1 gemobed -s
lc2 gemobed -scode -v
lc1 gemoblib -s
lc2 gemoblib -scode -v
lc1 gemfmalt -s
lc2 gemfmalt -scode -v
lc1 gemfmlib -s
lc2 gemfmlib -scode -v
lc1 gemsclib -s
lc2 gemsclib -scode -v
lc1 gemfslib -s
lc2 gemfslib -scode -v
lc1 gemwmlib -s
lc2 gemwmlib -scode -v
lc1 gemrslib -s
lc2 gemrslib -scode -v
lc1 gemshlib -s
lc2 gemshlib -scode -v
lc1 gemgrlib -s
lc2 gemgrlib -scode -v
lc1 gemgsxif -s
lc2 gemgsxif -scode -v
lc1 gemglobe -s
lc2 gemglobe -scode -v
lc1 gemgraf -s
lc2 gemgraf -scode -v
lc1 optimize -s
lc2 optimize -scode -v
rasm86 gemstart $pz
rasm86 gemgmain $pz
rasm86 gsx2 $pz
rasm86 large $pz
rasm86 gemdosif $pz
rasm86 gemasm $pz
rasm86 gemobjop $pz
rasm86 optimopt $pz
rasm86 proend $pz
link86 gem30[i
