/*	DESKMENU.H	05/04/84 - 10/09/84	Lee Lorenzen		*/

/*
*       Copyright 1999, Caldera Thin Clients, Inc.                      
*       This software is licenced under the GNU Public License.         
*       Please see LICENSE.TXT for further information.                 
*                                         
*/

#define NUM_OBS 42		/* objects		*/
#define NUM_TI 34		/* tedinfo blocks	*/

#define	THESCREEN 0
#define THEMENUS 1
#define THEBAR 2
#define THEACTIVE 3

#define DESKMENU 4
#define FILEMENU 5
#define VIEWMENU 6
#define OPTNMENU 7

#define ABOUITEM 9
#define L1ITEM 10           
#define DSK1ITEM 11
#define DSK2ITEM 12          
#define DSK3ITEM 13
#define DSK4ITEM 14      
#define DSK5ITEM 15     
#define DSK6ITEM 16   

#define OPENITEM 18
#define SHOWITEM 19
#define L2ITEM 20
#define NEWFITEM 21
#define CLSFITEM 22
#define CLSWITEM 23 
#define L3ITEM 24
#define FORMITEM 25
#define OUTPITEM 26
#define QUITITEM 27   

#define ICONITEM 29
#define TEXTITEM 30
#define L4ITEM 31
#define NAMEITEM 32
#define DATEITEM 33
#define SIZEITEM 34
#define TYPEITEM 35
/* #define SHALITEM 36	*/

#define IDSKITEM 38
#define IAPPITEM 39
#define L5ITEM 40
#define PREFITEM 41
