/*
*       Copyright 1999, Caldera Thin Clients, Inc.                      
*       This software is licenced under the GNU Public License.         
*       Please see LICENSE.TXT for further information.                 
*                                        
*/

#define STNOAPPL 17  	/* STRING */
#define STNOWIND 18  	/* STRING */
#define STS1 19  	/* STRING */
#define STFORMAT 20  	/* STRING */
#define STBADCOP 21  	/* STRING */
#define STS2 22  	/* STRING */
#define STDELDIS 23  	/* STRING */
#define STAPGONE 24  	/* STRING */
#define STS3 25  	/* STRING */
#define STS4 26  	/* STRING */
#define STFOEXIS 27  	/* STRING */
#define STDISKFU 28  	/* STRING */
#define STNOFILE 29  	/* STRING */
#define STNOINF 30  	/* STRING */
#define STFO8DEE 31  	/* STRING */
#define STDEEPPA 32  	/* STRING */
#define ADMENU 0  	/* TREE */
#define ADFILEIN 1  	/* TREE */
#define ADDISKIN 2  	/* TREE */
#define ADFOLDIN 4  	/* TREE */
#define ADNFINFO 5  	/* TREE */
#define ADOPENAP 6  	/* TREE */
#define ADINSDIS 7  	/* TREE */
#define ADINSAPP 8  	/* TREE */
#define ADCOPYDI 9  	/* TREE */
#define ADDELEDI 10  	/* TREE */
#define ADCPALER 11  	/* TREE */
#define ADMKDBOX 12  	/* TREE */
#define ADSETPRE 13  	/* TREE */
#define DESKMENU 3  	/* OBJECT in TREE #0 */
#define FILEMENU 4  	/* OBJECT in TREE #0 */
#define OPTNMENU 5  	/* OBJECT in TREE #0 */
#define VIEWMENU 6  	/* OBJECT in TREE #0 */
#define ABOUITEM 9  	/* OBJECT in TREE #0 */
#define OPENITEM 18  	/* OBJECT in TREE #0 */
#define SHOWITEM 19  	/* OBJECT in TREE #0 */
#define CLSFITEM 20  	/* OBJECT in TREE #0 */
#define DELTITEM 21  	/* OBJECT in TREE #0 */
#define FORMITEM 22  	/* OBJECT in TREE #0 */
#define OUTPITEM 24  	/* OBJECT in TREE #0 */
#define L3ITEM 23  	/* OBJECT in TREE #0 */
#define QUITITEM 25  	/* OBJECT in TREE #0 */
#define IDSKITEM 28  	/* OBJECT in TREE #0 */
#define IAPPITEM 29  	/* OBJECT in TREE #0 */
#define L5ITEM 31  	/* OBJECT in TREE #0 */
#define PREFITEM 32  	/* OBJECT in TREE #0 */
#define SAVEITEM 33  	/* OBJECT in TREE #0 */
#define DOSITEM 34  	/* OBJECT in TREE #0 */
#define ICONITEM 36  	/* OBJECT in TREE #0 */
#define L4ITEM 37  	/* OBJECT in TREE #0 */
#define NAMEITEM 38  	/* OBJECT in TREE #0 */
#define TYPEITEM 39  	/* OBJECT in TREE #0 */
#define SIZEITEM 40  	/* OBJECT in TREE #0 */
#define DATEITEM 41  	/* OBJECT in TREE #0 */
#define FITITLE 1  	/* OBJECT in TREE #1 */
#define FINAME 2  	/* OBJECT in TREE #1 */
#define FISIZE 3  	/* OBJECT in TREE #1 */
#define FIDATE 4  	/* OBJECT in TREE #1 */
#define FITIME 5  	/* OBJECT in TREE #1 */
#define FIATTRS 6  	/* OBJECT in TREE #1 */
#define FIRWRITE 8  	/* OBJECT in TREE #1 */
#define FIRONLY 9  	/* OBJECT in TREE #1 */
#define FIOK 10  	/* OBJECT in TREE #1 */
#define FICNCL 11  	/* OBJECT in TREE #1 */
#define DITITLE 1  	/* OBJECT in TREE #2 */
#define DIDRIVE 2  	/* OBJECT in TREE #2 */
#define DIVOLUME 3  	/* OBJECT in TREE #2 */
#define DINFOLDS 4  	/* OBJECT in TREE #2 */
#define DINFILES 5  	/* OBJECT in TREE #2 */
#define DIUSED 6  	/* OBJECT in TREE #2 */
#define DIAVAIL 7  	/* OBJECT in TREE #2 */
#define DIOK 8  	/* OBJECT in TREE #2 */
#define INSAPP 1  	/* OBJECT in TREE #8 */
#define APNAME 2  	/* OBJECT in TREE #8 */
#define APDOCU 3  	/* OBJECT in TREE #8 */
#define APDFTYPE 4  	/* OBJECT in TREE #8 */
#define APTYPE 12  	/* OBJECT in TREE #8 */
#define APGEM 14  	/* OBJECT in TREE #8 */
#define APDOS 15  	/* OBJECT in TREE #8 */
#define APPARMS 16  	/* OBJECT in TREE #8 */
#define APMEM 17  	/* OBJECT in TREE #8 */
#define APMEMBOX 18  	/* OBJECT in TREE #8 */
#define APYMEM 19  	/* OBJECT in TREE #8 */
#define APNMEM 20  	/* OBJECT in TREE #8 */
#define APMEMSZ 21  	/* OBJECT in TREE #8 */
#define APICON 22  	/* OBJECT in TREE #8 */
#define APFTITLE 23  	/* OBJECT in TREE #8 */
#define APFUPARO 28  	/* OBJECT in TREE #8 */
#define APFDNARO 29  	/* OBJECT in TREE #8 */
#define APINST 32  	/* OBJECT in TREE #8 */
#define APREMV 33  	/* OBJECT in TREE #8 */
#define APCNCL 34  	/* OBJECT in TREE #8 */
#define APFILEBO 24  	/* OBJECT in TREE #8 */
#define APF1NAME 25  	/* OBJECT in TREE #8 */
#define APF2NAME 26  	/* OBJECT in TREE #8 */
#define APSCRLBA 27  	/* OBJECT in TREE #8 */
#define APFSVSLI 30  	/* OBJECT in TREE #8 */
#define APFSVELE 31  	/* OBJECT in TREE #8 */
#define DRID 2  	/* OBJECT in TREE #7 */
#define DRDINS 1  	/* OBJECT in TREE #7 */
#define DRLABEL 3  	/* OBJECT in TREE #7 */
#define DRTYPE 4  	/* OBJECT in TREE #7 */
#define DRBUTNS 5  	/* OBJECT in TREE #7 */
#define DRFLOPPY 6  	/* OBJECT in TREE #7 */
#define DRHARD 7  	/* OBJECT in TREE #7 */
#define DRINST 8  	/* OBJECT in TREE #7 */
#define DRREM 9  	/* OBJECT in TREE #7 */
#define DRCNCL 10  	/* OBJECT in TREE #7 */
#define MKNAME 2  	/* OBJECT in TREE #12 */
#define MKOK 3  	/* OBJECT in TREE #12 */
#define MKCNCL 4  	/* OBJECT in TREE #12 */
#define FOLINFO 1  	/* OBJECT in TREE #4 */
#define FOLNAME 2  	/* OBJECT in TREE #4 */
#define FOLDATE 3  	/* OBJECT in TREE #4 */
#define FOLTIME 4  	/* OBJECT in TREE #4 */
#define FOLNFOLD 5  	/* OBJECT in TREE #4 */
#define FOLNFILE 6  	/* OBJECT in TREE #4 */
#define FOLSIZE 7  	/* OBJECT in TREE #4 */
#define FOLOK 8  	/* OBJECT in TREE #4 */
#define DDDELETE 1  	/* OBJECT in TREE #10 */
#define DDFOLDS 2  	/* OBJECT in TREE #10 */
#define DDFILES 3  	/* OBJECT in TREE #10 */
#define DDOK 4  	/* OBJECT in TREE #10 */
#define DDCNCL 5  	/* OBJECT in TREE #10 */
#define APPLOPEN 1  	/* OBJECT in TREE #6 */
#define APPLNAME 2  	/* OBJECT in TREE #6 */
#define APPLOK 4  	/* OBJECT in TREE #6 */
#define APPLCNCL 5  	/* OBJECT in TREE #6 */
#define APPLPARM 3  	/* OBJECT in TREE #6 */
#define NFINOK 7  	/* OBJECT in TREE #5 */
#define CDCOPY 1  	/* OBJECT in TREE #9 */
#define CDFOLDS 2  	/* OBJECT in TREE #9 */
#define CDFILES 3  	/* OBJECT in TREE #9 */
#define CDOK 4  	/* OBJECT in TREE #9 */
#define CDCNCL 5  	/* OBJECT in TREE #9 */
#define CACOPY 1  	/* OBJECT in TREE #11 */
#define CACURRNA 2  	/* OBJECT in TREE #11 */
#define CACOPYNA 3  	/* OBJECT in TREE #11 */
#define CAOK 4  	/* OBJECT in TREE #11 */
#define CACNCL 5  	/* OBJECT in TREE #11 */
#define CASTOP 6  	/* OBJECT in TREE #11 */
#define SPTITLE 1  	/* OBJECT in TREE #13 */
#define SPCNFDEL 2  	/* OBJECT in TREE #13 */
#define SPCDYES 4  	/* OBJECT in TREE #13 */
#define SPCDNO 5  	/* OBJECT in TREE #13 */
#define SPCNFCOP 6  	/* OBJECT in TREE #13 */
#define SPCCYES 8  	/* OBJECT in TREE #13 */
#define SPCCNO 9  	/* OBJECT in TREE #13 */
#define SPDCLICK 10  	/* OBJECT in TREE #13 */
#define SPDC1 12  	/* OBJECT in TREE #13 */
#define SPDC2 13  	/* OBJECT in TREE #13 */
#define SPDC3 14  	/* OBJECT in TREE #13 */
#define SPDC4 15  	/* OBJECT in TREE #13 */
#define SPDC5 16  	/* OBJECT in TREE #13 */
#define SPSEYES 19  	/* OBJECT in TREE #13 */
#define SPSENO 20  	/* OBJECT in TREE #13 */
#define SPOK 21  	/* OBJECT in TREE #13 */
#define SPCNCL 22  	/* OBJECT in TREE #13 */
#define STINFOST 0		/* FREE STRING */
#define STASICON 1		/* FREE STRING */
#define STAPPL 2		/* FREE STRING */
#define STDOCU 3		/* FREE STRING */
#define STDKFORM 4		/* FREE STRING */
#define STASTEXT 5		/* FREE STRING */
#define STGEMHIC 6		/* FREE STRING */
#define STGEMAPP 7		/* FREE STRING */
#define STGEMLOI 8		/* FREE STRING */
#define STGEMOUT 9		/* FREE STRING */
#define STGEMBAT 10		/* FREE STRING */
#define ST1STD 11		/* FREE STRING */
#define ST2STD 12		/* FREE STRING */
#define ST3STD 13		/* FREE STRING */
#define ST4STD 14		/* FREE STRING */
#define ST5STD 15		/* FREE STRING */
#define ST6STD 16		/* FREE STRING */
#define ADINSACC 14  	/* TREE */
#define IACCITEM 30  	/* OBJECT in TREE #0 */
#define ACA1NAME 4  	/* OBJECT in TREE #14 */
#define ACA2NAME 5  	/* OBJECT in TREE #14 */
#define ACA3NAME 6  	/* OBJECT in TREE #14 */
#define ACA4NAME 7  	/* OBJECT in TREE #14 */
#define ACA5NAME 8  	/* OBJECT in TREE #14 */
#define ACA6NAME 9  	/* OBJECT in TREE #14 */
#define ACA7NAME 10  	/* OBJECT in TREE #14 */
#define ACA8NAME 11  	/* OBJECT in TREE #14 */
#define ACINST 17  	/* OBJECT in TREE #14 */
#define ACCNCL 18  	/* OBJECT in TREE #14 */
#define ACREMV 23  	/* OBJECT in TREE #14 */
#define ACC1NAME 20  	/* OBJECT in TREE #14 */
#define ACC2NAME 21  	/* OBJECT in TREE #14 */
#define ACC3NAME 22  	/* OBJECT in TREE #14 */
#define ACFUPARO 13  	/* OBJECT in TREE #14 */
#define ACFDNARO 14  	/* OBJECT in TREE #14 */
#define ACFSELEV 16  	/* OBJECT in TREE #14 */
#define ACFSVSLI 15  	/* OBJECT in TREE #14 */
#define ACC1FMEM 26  	/* OBJECT in TREE #14 */
#define ACC2FMEM 27  	/* OBJECT in TREE #14 */
#define ACC3FMEM 28  	/* OBJECT in TREE #14 */
#define STACCMEM 33  	/* STRING */
#define DBUGITEM 26  	/* OBJECT in TREE #0 */
#define ACNAMBOX 3  	/* OBJECT in TREE #14 */
#define SPTF12HR 26  	/* OBJECT in TREE #13 */
#define SPTF24HR 27  	/* OBJECT in TREE #13 */
#define SPDFMMDD 29  	/* OBJECT in TREE #13 */
#define SPDFDDMM 30  	/* OBJECT in TREE #13 */
#define ADDINFO 3  	/* TREE */
#define DEOK 2  	/* OBJECT in TREE #3 */
#define DEICON 3  	/* OBJECT in TREE #3 */
#define DEMEMSIZ 5  	/* OBJECT in TREE #3 */
#define DENAME1 10  	/* OBJECT in TREE #3 */
#define DENAME2 15  	/* OBJECT in TREE #3 */
#define DENAME3 16  	/* OBJECT in TREE #3 */
#define DENAME4 17  	/* OBJECT in TREE #3 */
#define STACFMEM 34  	/* STRING */
#define STNOFSTP 35  	/* STRING */
#define STNOROOM 36  	/* STRING */
#define ADLRSINF 15  	/* TREE */
#define LDEICON 1  	/* OBJECT in TREE #15 */
#define LDENAME1 2  	/* OBJECT in TREE #15 */
#define LDENAME2 3  	/* OBJECT in TREE #15 */
#define LDENAME3 4  	/* OBJECT in TREE #15 */
#define LDENAME4 5  	/* OBJECT in TREE #15 */
