rasm deskstar $pzsz
rasm deskos30 $pzsz
rasm gsx2 $pzsz
rasm longasm $pzsz
rasm rtlasm $pzsznc
rasm proend $pzsz
hc desktop
hc desksupp
hc deskrsrc
hc deskapp
hc deskiacc
hc deskact
hc deskfun
hc deskdir
hc deskinf
hc deskins
hc deskwin
hc deskobj
hc deskfpd
hc deskpro
hc deskif
hc deskgraf
hc deskgsx
hc gembind
hc gemdos
hc optimize
hc optimopt
hc deskglob
hc hcsmall
link86 desktop[i]
