/********************************************************************
*
*  GEM/3 Programmers Toolkit - Digital Research, Inc.
*
*  Filename: XFORM.H
*
*  Date: 08/01/89
*
*********************************************************************/

#define MAINMENU 0  	/* TREE */
#define QUITITEM 17  	/* OBJECT in TREE #0 */
#define ABOUITEM 8  	/* OBJECT in TREE #0 */
#define VIEWITEM 19  	/* OBJECT in TREE #0 */
#define NWINDOW 0  	/* STRING */
#define ABOUDIAL 1  	/* TREE */
#define ABOUOK 2  	/* OBJECT in TREE #1 */
#define FITDIAL 2  	/* TREE */
#define FULLITEM 3  	/* OBJECT in TREE #2 */
#define SVASITEM 6  	/* OBJECT in TREE #2 */
#define IGASITEM 7  	/* OBJECT in TREE #2 */
#define FITOK 16  	/* OBJECT in TREE #2 */
#define ZOM2ITEM 4  	/* OBJECT in TREE #2 */
#define ZOM3ITEM 5  	/* OBJECT in TREE #2 */
